### ISSUE TITLE
Failure to self manage statement handles causes DBDish::Oracle: Error: ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by ancientwizard** [raku-community-modules/DBIish#210]
Built-in operation automations such as ".do", ".execute", ".commit", ".rollback" and perhaps others fail to clean up handles they create and use causing Oracle to run out of cursors over time. Keep in mind the fix for this issue also requires the fixes for issue #209 which makes .dispose on statement handles successfully release.

**Comment by ancientwizard** [comment]
I've patched this issue; but as I mentioned the complete solution requires the fix for #209 as well otherwise the newly added caching and .dispose method calling will be fruitless.

**Comment by jonathanstowe** [comment]
Please make a PR.

**Comment by jonathanstowe** [comment]
@raiph you're cool chief :+1: 

@ancientwizard It may have been more helpful if I had added more explanation.  There is probably a small handful of people who would be confident in reviewing work on the Oracle driver and I wouldn't consider myself amongst those (I've got changes in it related to the original merge but that's it.)  No-one is likely to want to merge anything without there having been a couple of eyes on it first. Without a pull request the changes don't have any proper visibility to anyone who may have any input to make, and if someone wants to make a review of the code they would need to pull your branch and examine the diff, if they wish to make some feedback or request some changes then there wouldn't really be any convenient method of doing so that would relate them to the original changes.  Making a pull request means that more people will see the change, review and make feedback and consequently make it more likely that the changes will get merged.  Without a PR the only way that the work will get merged is if someone were to do it unilaterally (unlikely,) or if  someone else were to create a branch in this repository with the changes and make a PR from *that* and have it reviewed etc.  So please make a PR, the work looks like it would be of benefit and it would be a shame if it were to be overlooked.
