### ISSUE TITLE
kebab-case

### ISSUE THREAD

**Issue by tokuhirom** [raku-community-modules/DBIish#22]
There's some lower_case methods. I suggest to rename these methods before christmas.

**Comment by azawawi** [comment]
Do we need to keep the old ones as deprecated and add the new ones?

**Comment by moritz** [comment]
yes please. And rethink the method names in general. Anything with *ref* is suspicious.

Oh, and we have lazy lists now. Which means that 

    while my @row = $sth.fetchrow_array {...} 

Should really be

     for $sth.rows -> @row { ... }

And if one wants the row as a hash, it should probably be `$sth.rows(:hash)`.

**Comment by Skarsnik** [comment]
I am actually playing around with this in DBI (deprecating all the fetch**) 

There is one issue with using `rows` . it's already used to get the number of rows affected/returned by the statement.

For now I will try with `row` and `allrows` (with the :hash adverb). There is also the issue of https://github.com/perl6/DBIish/issues/31 Since every sane drivers provide a way to get the type of the column, I was thinking of the 'modern perl6' method (aka `row` and `allrows`) always returning a typed value with this, since everything has a .Str method

There is also another issue. What to do with large string field or blob field? We can return a copy but it's probably not really ram friendly, but if we return what the C lib give us, it can became easily lost memory since (in case of Pg for example) we need to call a clear routine on this.

**Comment by Skarsnik** [comment]
I did not figure how to have for $sth.row -> @row work with having $std.row only returning one result for now.
You can have a look at https://github.com/Skarsnik/DBIish For now I keep all the old stuff and just deprecated nearly every fetch* stuff. (Only Pg/SQLite have `row`)
For the `$sth.allrows()` I am planning of having a allrows(:array-of-hash) and allrows(:hash-of-array) 'option' to be able to choose how you want the data with a hash form.

I am not sure if all *ref are really useful in perl6, so I just forget about them.

**Comment by Skarsnik** [comment]
Should I close that and deprecate all the _ to keep only the kebab cased method?

**Comment by Row** [comment]
Ok

**Comment by rbt** [comment]
The old DBI fetch* stuff was deprecated in d0c1d05 and the README has been updated since. I think everything in this discussion is complete.

The internal code is still a mix of underscore, kebab-case and dashed variables but that seems a separate issue.
